import "./css/icon.css"
import "./css/vendors.css"
import "./css/style.css"
import "./css/responsive.css"
import "./css/digital-agency.css"
import MusicPlayer from "@/components/MusicPlayer/MusicPlayer"
import { MusicPlayerProvider } from "@/components/MusicPlayer/MusicPlayerProvider"

export const metadata = {
  title: "Vanderpump Tech | Web & App Development",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="no-js" lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <link rel="shortcut icon" href="favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin="true" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      </head>
      <body>
        <MusicPlayerProvider>
          {children}
          <MusicPlayer />
        </MusicPlayerProvider>
      </body>
    </html>
  );
}
